version: '2'
services:
    tulio-postcoder-redis:
        build: ./redis
        
    tulio-postcoder-api:
        image: tuliocastro/postcoder-api
        external_links:
            - tulio-postcoder-redis:rediscache
        ports:
            - 8080:8080
        links:
            - tulio-postcoder-redis:rediscache
            
    tulio-postcoder-front:
        build: ./front/docker
        ports:
            - "80:80"
        
            
            
    
    
    